// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

//! Metrics codegen orchestration.
//!
//! `cargo xtask generate-metrics` discovers `metrics_schema.yaml` files,
//! parses them, and renders Rust code via MiniJinja templates.

pub mod ir;
pub mod schema;

use schema::ResolvedMetricSet;
use std::path::{Path, PathBuf};

const LEVEL_NAMES: &[&str] = &["Basic", "Normal", "Detailed"];

/// Get the level layout for a metric by level name.
fn get_set_level_layout<'a>(set: &'a ResolvedMetricSet, level: &str) -> &'a ir::ResolvedLevelLayout {
    match level {
        "Basic" => &set.levels.basic,
        "Normal" => &set.levels.normal,
        "Detailed" => &set.levels.detailed,
        _ => unreachable!(),
    }
}

/// Discover all `metrics_schema.yaml` files under the crates directory.
fn discover_schemas(workspace_root: &Path) -> Vec<PathBuf> {
    let crates_dir = workspace_root.join("crates");
    let mut schemas = Vec::new();
    if let Ok(entries) = std::fs::read_dir(&crates_dir) {
        for entry in entries.flatten() {
            let candidate = entry.path().join("metrics_schema.yaml");
            if candidate.exists() {
                schemas.push(candidate);
            }
        }
    }
    schemas.sort();
    schemas
}

/// Run the full generate-metrics pipeline.
pub fn run(check_only: bool) -> anyhow::Result<()> {
    let workspace_root = Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap();
    let schemas = discover_schemas(workspace_root);

    if schemas.is_empty() {
        println!("No metrics_schema.yaml files found.");
        return Ok(());
    }

    for schema_path in &schemas {
        println!("📐 Processing {}", schema_path.display());
        let (_schema, resolved_sets) = schema::parse_and_resolve(schema_path)?;

        // Determine output directory (same directory as the schema file).
        let crate_dir = schema_path.parent().unwrap();
        let output_dir = crate_dir.join("src").join("self_metrics");
        std::fs::create_dir_all(&output_dir)?;

        let output_path = output_dir.join("generated.rs");
        let generated = render_generated_code(&resolved_sets)?;

        if check_only {
            // Compare with existing file.
            if output_path.exists() {
                let existing = std::fs::read_to_string(&output_path)?;
                if existing != generated {
                    anyhow::bail!(
                        "Generated code is stale: {}. Run `cargo xtask generate-metrics` to update.",
                        output_path.display()
                    );
                }
            } else {
                anyhow::bail!(
                    "Generated file missing: {}. Run `cargo xtask generate-metrics` to create.",
                    output_path.display()
                );
            }
            println!("  ✅ {} is up to date.", output_path.display());
        } else {
            std::fs::write(&output_path, &generated)?;
            println!("  ✍️  Wrote {}", output_path.display());
        }
    }

    Ok(())
}

/// Render the generated Rust code for a set of resolved metric sets.
///
/// This is a direct code-generation approach (string building) rather than
/// MiniJinja templates, for simplicity in the prototype phase. Templates
/// can be introduced later when the generated output stabilizes.
fn render_generated_code(sets: &[ResolvedMetricSet]) -> anyhow::Result<String> {
    let mut out = String::new();

    out.push_str(
        "// Copyright The OpenTelemetry Authors\n\
         // SPDX-License-Identifier: Apache-2.0\n\
         \n\
         // @generated by `cargo xtask generate-metrics` — do not edit manually.\n\
         \n\
         #![allow(dead_code)]\n\
         #![allow(missing_docs)]\n\
         #![allow(trivial_numeric_casts)]\n\
         #![allow(clippy::needless_update)]\n\
         \n\
         use otap_df_config::policy::MetricLevel;\n\
         use crate::instrument::Counter;\n\
         \n",
    );

    for set in sets {
        render_metric_set(&mut out, set)?;
    }

    Ok(out)
}

fn render_metric_set(out: &mut String, set: &ResolvedMetricSet) -> anyhow::Result<()> {
    let struct_name = to_pascal_case(&set.id);

    // Generate dimension cardinality constants (shared across the set).
    for dim in &set.dimensions {
        render_dimension_constants(out, dim);
    }

    // Generate the level-aware metric set enum.
    out.push_str(&format!("/// {}\n", set.brief));
    out.push_str(&format!("pub enum {struct_name} {{\n"));

    for level_name in LEVEL_NAMES {
        let layout = get_set_level_layout(set, level_name);
        let n = layout.num_scopes; // All metrics share this size.
        let fields: Vec<String> = set
            .metrics
            .iter()
            .map(|m| {
                let field_name = metric_field_name(&m.def.name);
                match m.def.recording_mode {
                    ir::RecordingMode::Counting => {
                        if m.def.value_type == ir::ValueType::U64 {
                            format!("        {field_name}: [Counter<u64>; {n}]")
                        } else {
                            format!("        {field_name}: [Counter<f64>; {n}]")
                        }
                    }
                    ir::RecordingMode::Histogram => {
                        format!("        {field_name}: [Counter<f64>; {n}]")
                    }
                    ir::RecordingMode::LastValue => {
                        if m.def.value_type == ir::ValueType::U64 {
                            format!("        {field_name}: [u64; {n}]")
                        } else {
                            format!("        {field_name}: [f64; {n}]")
                        }
                    }
                }
            })
            .collect();

        out.push_str(&format!("    /// Active at `MetricLevel::{level_name}` ({n} scopes).\n"));
        out.push_str(&format!("    {level_name} {{\n"));
        for field in &fields {
            out.push_str(field);
            out.push_str(",\n");
        }
        out.push_str("    },\n");
    }
    out.push_str("}\n\n");

    // Generate impl block.
    out.push_str(&format!("impl {struct_name} {{\n"));

    // Constructor.
    out.push_str("    /// Create a new metric set for the given level.\n");
    out.push_str("    #[must_use]\n");
    out.push_str("    pub fn new(level: MetricLevel) -> Self {\n");
    out.push_str("        match level {\n");

    for (level_variant, level_match) in [
        ("Basic", "MetricLevel::None | MetricLevel::Basic"),
        ("Normal", "MetricLevel::Normal"),
        ("Detailed", "MetricLevel::Detailed"),
    ] {
        out.push_str(&format!("            {level_match} => Self::{level_variant} {{\n"));
        for m in &set.metrics {
            let field_name = metric_field_name(&m.def.name);
            out.push_str(&format!(
                "                {field_name}: Default::default(),\n"
            ));
        }
        out.push_str("            },\n");
    }
    out.push_str("        }\n");
    out.push_str("    }\n\n");

    // Generate add/record methods for each metric.
    for metric in &set.metrics {
        render_metric_method(out, metric, set)?;
    }

    // Generate snapshot_into.
    render_snapshot_into(out, set)?;

    // Generate clear.
    render_clear(out, set)?;

    // Generate needs_flush.
    render_needs_flush(out, set)?;

    out.push_str("}\n\n");
    Ok(())
}

fn render_dimension_constants(out: &mut String, dim: &ir::ResolvedDimension) {
    // Already rendered? Skip duplicates.
    let const_prefix = dim.id.to_uppercase();
    let marker = format!("const {const_prefix}_CARDINALITY");
    if out.contains(&marker) {
        return;
    }

    out.push_str(&format!(
        "pub const {const_prefix}_CARDINALITY: usize = {};\n",
        dim.cardinality
    ));
    out.push('\n');
}

fn render_metric_method(
    out: &mut String,
    metric: &ir::ResolvedMetric,
    set: &ResolvedMetricSet,
) -> anyhow::Result<()> {
    let method_name = match metric.def.recording_mode {
        ir::RecordingMode::Counting => format!("add_{}", metric_field_name(&metric.def.name)),
        ir::RecordingMode::Histogram => format!("record_{}", metric_field_name(&metric.def.name)),
        ir::RecordingMode::LastValue => format!("set_{}", metric_field_name(&metric.def.name)),
    };

    // Dimension parameters come from the set (shared by all metrics).
    let dim_params: Vec<String> = set
        .dimensions
        .iter()
        .map(|d| format!("{}: usize", d.id))
        .collect();

    let value_type = match metric.def.recording_mode {
        ir::RecordingMode::Counting => {
            if metric.def.value_type == ir::ValueType::U64 {
                "u64"
            } else {
                "f64"
            }
        }
        ir::RecordingMode::Histogram => "f64",
        ir::RecordingMode::LastValue => {
            if metric.def.value_type == ir::ValueType::U64 {
                "u64"
            } else {
                "f64"
            }
        }
    };

    let params = if dim_params.is_empty() {
        format!("&mut self, value: {value_type}")
    } else {
        format!("&mut self, value: {value_type}, {}", dim_params.join(", "))
    };

    out.push_str(&format!("    /// Record a value for `{}`.\n", metric.def.name));
    out.push_str(&format!("    #[inline]\n"));
    out.push_str(&format!("    pub fn {method_name}({params}) {{\n"));

    let field_name = metric_field_name(&metric.def.name);
    let struct_name = to_pascal_case(&set.id);

    out.push_str(&format!("        match self {{\n"));

    for level_variant in LEVEL_NAMES {
        let layout = get_set_level_layout(set, level_variant);
        let index_expr = build_index_expr(&set.dimensions, &layout.active_dimensions);

        out.push_str(&format!(
            "            {struct_name}::{level_variant} {{ {field_name}, .. }} => {{\n"
        ));

        match metric.def.recording_mode {
            ir::RecordingMode::Counting | ir::RecordingMode::Histogram => {
                out.push_str(&format!(
                    "                {field_name}[{index_expr}].add(value);\n"
                ));
            }
            ir::RecordingMode::LastValue => {
                out.push_str(&format!(
                    "                {field_name}[{index_expr}] = value;\n"
                ));
            }
        }
        out.push_str("            }\n");
    }

    out.push_str("        }\n");
    out.push_str("    }\n\n");
    Ok(())
}

fn render_snapshot_into(out: &mut String, set: &ResolvedMetricSet) -> anyhow::Result<()> {
    let struct_name = to_pascal_case(&set.id);

    out.push_str("    /// Copy current values into a flat snapshot buffer.\n");
    out.push_str("    pub fn snapshot_into(&self, dest: &mut [u64]) {\n");
    out.push_str("        let mut offset = 0;\n");
    out.push_str("        match self {\n");

    for level_variant in ["Basic", "Normal", "Detailed"] {
        let fields: Vec<String> = set.metrics.iter().map(|m| metric_field_name(&m.def.name)).collect();
        let field_bindings = fields.join(", ");
        out.push_str(&format!(
            "            {struct_name}::{level_variant} {{ {field_bindings} }} => {{\n"
        ));
        for m in &set.metrics {
            let field_name = metric_field_name(&m.def.name);
            match m.def.recording_mode {
                ir::RecordingMode::Counting | ir::RecordingMode::Histogram => {
                    let cast = if m.def.value_type == ir::ValueType::U64 && m.def.recording_mode == ir::RecordingMode::Counting {
                        "" // u64 Counter → u64 dest, no cast
                    } else {
                        " as u64"
                    };
                    out.push_str(&format!(
                        "                for c in {field_name}.iter() {{\n\
                         \x20                   dest[offset] = c.get(){cast};\n\
                         \x20                   offset += 1;\n\
                         \x20               }}\n"
                    ));
                }
                ir::RecordingMode::LastValue => {
                    let cast = if m.def.value_type == ir::ValueType::U64 { "" } else { " as u64" };
                    out.push_str(&format!(
                        "                for &v in {field_name}.iter() {{\n\
                         \x20                   dest[offset] = v{cast};\n\
                         \x20                   offset += 1;\n\
                         \x20               }}\n"
                    ));
                }
            }
        }
        out.push_str("            }\n");
    }

    out.push_str("        }\n");
    out.push_str("    }\n\n");
    Ok(())
}

fn render_clear(out: &mut String, set: &ResolvedMetricSet) -> anyhow::Result<()> {
    let struct_name = to_pascal_case(&set.id);

    out.push_str("    /// Reset all values for the next collection interval.\n");
    out.push_str("    pub fn clear(&mut self) {\n");
    out.push_str("        match self {\n");

    for level_variant in ["Basic", "Normal", "Detailed"] {
        let fields: Vec<String> = set.metrics.iter().map(|m| metric_field_name(&m.def.name)).collect();
        let field_bindings = fields.join(", ");
        out.push_str(&format!(
            "            {struct_name}::{level_variant} {{ {field_bindings} }} => {{\n"
        ));
        for m in &set.metrics {
            let field_name = metric_field_name(&m.def.name);
            match m.def.recording_mode {
                ir::RecordingMode::Counting | ir::RecordingMode::Histogram => {
                    out.push_str(&format!(
                        "                for c in {field_name}.iter_mut() {{ c.reset(); }}\n"
                    ));
                }
                ir::RecordingMode::LastValue => {
                    let zero = if m.def.value_type == ir::ValueType::U64 { "0u64" } else { "0.0f64" };
                    out.push_str(&format!(
                        "                for v in {field_name}.iter_mut() {{ *v = {zero}; }}\n"
                    ));
                }
            }
        }
        out.push_str("            }\n");
    }

    out.push_str("        }\n");
    out.push_str("    }\n\n");
    Ok(())
}

fn render_needs_flush(out: &mut String, set: &ResolvedMetricSet) -> anyhow::Result<()> {
    let struct_name = to_pascal_case(&set.id);

    out.push_str("    /// Returns `true` if any value is non-zero.\n");
    out.push_str("    pub fn needs_flush(&self) -> bool {\n");
    out.push_str("        match self {\n");

    for level_variant in ["Basic", "Normal", "Detailed"] {
        let fields: Vec<String> = set.metrics.iter().map(|m| metric_field_name(&m.def.name)).collect();
        let field_bindings = fields.join(", ");
        out.push_str(&format!(
            "            {struct_name}::{level_variant} {{ {field_bindings} }} => {{\n"
        ));
        let mut checks = Vec::new();
        for m in &set.metrics {
            let field_name = metric_field_name(&m.def.name);
            match m.def.recording_mode {
                ir::RecordingMode::Counting => {
                    let zero = if m.def.value_type == ir::ValueType::U64 { "0u64" } else { "0.0f64" };
                    checks.push(format!("{field_name}.iter().any(|c| c.get() != {zero})"));
                }
                ir::RecordingMode::Histogram => {
                    checks.push(format!("{field_name}.iter().any(|c| c.get() != 0.0f64)"));
                }
                ir::RecordingMode::LastValue => {
                    let zero = if m.def.value_type == ir::ValueType::U64 { "0u64" } else { "0.0f64" };
                    checks.push(format!("{field_name}.iter().any(|&v| v != {zero})"));
                }
            }
        }
        out.push_str(&format!("                {}\n", checks.join("\n                    || ")));
        out.push_str("            }\n");
    }

    out.push_str("        }\n");
    out.push_str("    }\n");
    Ok(())
}

/// Build an index expression for array access given active dimensions.
///
/// For a single dimension `outcome`, produces: `outcome`
/// For two dimensions `outcome × signal_type`, produces:
///   `outcome * SIGNAL_TYPE_CARDINALITY + signal_type`
fn build_index_expr(all_dims: &[ir::ResolvedDimension], active: &[usize]) -> String {
    if active.is_empty() {
        return "0".to_string();
    }
    if active.len() == 1 {
        return all_dims[active[0]].id.clone();
    }

    // Row-major indexing: first dimension is most significant.
    let mut parts = Vec::new();
    for (i, &dim_idx) in active.iter().enumerate() {
        let dim_name = &all_dims[dim_idx].id;
        // Multiply by the product of all subsequent active dimensions' cardinalities.
        let suffix_product: usize = active[i + 1..]
            .iter()
            .map(|&j| all_dims[j].cardinality)
            .product();
        if suffix_product == 1 {
            parts.push(dim_name.clone());
        } else {
            parts.push(format!("{dim_name} * {suffix_product}"));
        }
    }
    parts.join(" + ")
}

// ── Helpers ─────────────────────────────────────────────────────────

/// Convert a snake_case identifier to PascalCase.
fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(c) => c.to_uppercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

/// Convert a dotted metric name to a snake_case field name.
/// e.g., "node.consumer.items" → "items"
fn metric_field_name(name: &str) -> String {
    name.rsplit('.').next().unwrap_or(name).to_string()
}
