[package]
name = "otel-arrow-dfe-sparkplug"
description = "Standalone Sparkplug protocol state machine"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
prost = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }
protoc-bin-vendored = "3"
