//! Parquet receiver module for reading parquet files and reconstructing OTAP data
//! 
//! This module provides functionality to read parquet files generated by the 
//! `parquet_exporter` and reconstruct OTAP data for pipeline processing.

pub mod config;
pub mod error;
pub mod file_discovery;
pub mod query_engine; 
pub mod reconstruction;