
//! Generated counter metric set code.
//!
//! DO NOT EDIT — generated by `cargo xtask generate-metrics`.

use otap_df_config::policy::MetricLevel;
use otap_df_config::SignalType;
use otap_df_metrics_sdk::dimension::{Dimension, Outcome};
use otap_df_metrics_sdk::precomputed::{CounterMetricDef, PrecomputedMetricSchema};
use crate::instrument::Counter;


/// Items consumed by this node.
///
/// Metric name: `node.consumer.items`
/// Unit: `{item}`
/// Instrument: counter
pub enum NodeConsumerItems {
    /// Disabled (MetricLevel::None).
    None,

    /// Basic level: 3 data points.
    /// Dimensions: outcome.
    Basic([Counter<u64>; 3]),

    /// Normal level: 9 data points.
    /// Dimensions: outcome, signal_type.
    Normal([Counter<u64>; 9]),

}

impl NodeConsumerItems {
    /// Create a new metric set for the given level.
    #[must_use]
    pub fn new(level: MetricLevel) -> Self {
        match level {
            MetricLevel::None => Self::None,

            MetricLevel::Basic => Self::Basic(Default::default()),

            MetricLevel::Normal => Self::Normal(Default::default()),

            MetricLevel::Detailed => Self::Normal(Default::default()),

        }
    }

    /// Add a value to the counter with the given dimension values.
    #[inline]
    pub fn add(
        &mut self,
        value: u64,

        outcome: Outcome,

        signal_type: SignalType,

    ) {
        match self {
            Self::None => {}

            Self::Basic(counters) => {
                let idx = outcome.index();
                counters[idx].add(value);
            }

            Self::Normal(counters) => {
                let idx = outcome.index() * 3 + signal_type.index();
                counters[idx].add(value);
            }

        }
    }

    /// Snapshot all counter values as a flat array.
    /// Returns `None` if the metric is disabled.
    #[must_use]
    pub fn snapshot(&self) -> Option<Vec<u64>> {
        match self {
            Self::None => None,

            Self::Basic(counters) => {
                Some(counters.iter().map(|c| c.get()).collect())
            }

            Self::Normal(counters) => {
                Some(counters.iter().map(|c| c.get()).collect())
            }

        }
    }

    /// Reset all counters to zero.
    pub fn clear(&mut self) {
        match self {
            Self::None => {}

            Self::Basic(counters) => {
                for c in counters.iter_mut() {
                    c.reset();
                }
            }

            Self::Normal(counters) => {
                for c in counters.iter_mut() {
                    c.reset();
                }
            }

        }
    }
}


/// Items produced by this node.
///
/// Metric name: `node.producer.items`
/// Unit: `{item}`
/// Instrument: counter
pub enum NodeProducerItems {
    /// Disabled (MetricLevel::None).
    None,

    /// Basic level: 3 data points.
    /// Dimensions: outcome.
    Basic([Counter<u64>; 3]),

    /// Normal level: 9 data points.
    /// Dimensions: outcome, signal_type.
    Normal([Counter<u64>; 9]),

}

impl NodeProducerItems {
    /// Create a new metric set for the given level.
    #[must_use]
    pub fn new(level: MetricLevel) -> Self {
        match level {
            MetricLevel::None => Self::None,

            MetricLevel::Basic => Self::Basic(Default::default()),

            MetricLevel::Normal => Self::Normal(Default::default()),

            MetricLevel::Detailed => Self::Normal(Default::default()),

        }
    }

    /// Add a value to the counter with the given dimension values.
    #[inline]
    pub fn add(
        &mut self,
        value: u64,

        outcome: Outcome,

        signal_type: SignalType,

    ) {
        match self {
            Self::None => {}

            Self::Basic(counters) => {
                let idx = outcome.index();
                counters[idx].add(value);
            }

            Self::Normal(counters) => {
                let idx = outcome.index() * 3 + signal_type.index();
                counters[idx].add(value);
            }

        }
    }

    /// Snapshot all counter values as a flat array.
    /// Returns `None` if the metric is disabled.
    #[must_use]
    pub fn snapshot(&self) -> Option<Vec<u64>> {
        match self {
            Self::None => None,

            Self::Basic(counters) => {
                Some(counters.iter().map(|c| c.get()).collect())
            }

            Self::Normal(counters) => {
                Some(counters.iter().map(|c| c.get()).collect())
            }

        }
    }

    /// Reset all counters to zero.
    pub fn clear(&mut self) {
        match self {
            Self::None => {}

            Self::Basic(counters) => {
                for c in counters.iter_mut() {
                    c.reset();
                }
            }

            Self::Normal(counters) => {
                for c in counters.iter_mut() {
                    c.reset();
                }
            }

        }
    }
}


/// Build the precomputed metric schema for the given level.
#[must_use]
pub fn precomputed_schema(level: MetricLevel) -> Option<PrecomputedMetricSchema> {
    let defs: Vec<CounterMetricDef> = match level {
        MetricLevel::None => return None,

        MetricLevel::Basic => vec![

            CounterMetricDef {
                name: "node.consumer.items",
                unit: "{item}",
                description: "Items consumed by this node.",
                num_points: 3,
                point_attributes: &[

                    ("outcome", "success"),

                    ("outcome", "failure"),

                    ("outcome", "refused"),

                ],
                attrs_per_point: 1,
            },

            CounterMetricDef {
                name: "node.producer.items",
                unit: "{item}",
                description: "Items produced by this node.",
                num_points: 3,
                point_attributes: &[

                    ("outcome", "success"),

                    ("outcome", "failure"),

                    ("outcome", "refused"),

                ],
                attrs_per_point: 1,
            },

        ],

        MetricLevel::Normal => vec![

            CounterMetricDef {
                name: "node.consumer.items",
                unit: "{item}",
                description: "Items consumed by this node.",
                num_points: 9,
                point_attributes: &[

                    ("outcome", "success"),

                    ("signal_type", "traces"),

                    ("outcome", "success"),

                    ("signal_type", "metrics"),

                    ("outcome", "success"),

                    ("signal_type", "logs"),

                    ("outcome", "failure"),

                    ("signal_type", "traces"),

                    ("outcome", "failure"),

                    ("signal_type", "metrics"),

                    ("outcome", "failure"),

                    ("signal_type", "logs"),

                    ("outcome", "refused"),

                    ("signal_type", "traces"),

                    ("outcome", "refused"),

                    ("signal_type", "metrics"),

                    ("outcome", "refused"),

                    ("signal_type", "logs"),

                ],
                attrs_per_point: 2,
            },

            CounterMetricDef {
                name: "node.producer.items",
                unit: "{item}",
                description: "Items produced by this node.",
                num_points: 9,
                point_attributes: &[

                    ("outcome", "success"),

                    ("signal_type", "traces"),

                    ("outcome", "success"),

                    ("signal_type", "metrics"),

                    ("outcome", "success"),

                    ("signal_type", "logs"),

                    ("outcome", "failure"),

                    ("signal_type", "traces"),

                    ("outcome", "failure"),

                    ("signal_type", "metrics"),

                    ("outcome", "failure"),

                    ("signal_type", "logs"),

                    ("outcome", "refused"),

                    ("signal_type", "traces"),

                    ("outcome", "refused"),

                    ("signal_type", "metrics"),

                    ("outcome", "refused"),

                    ("signal_type", "logs"),

                ],
                attrs_per_point: 2,
            },

        ],

        MetricLevel::Detailed => vec![

            CounterMetricDef {
                name: "node.consumer.items",
                unit: "{item}",
                description: "Items consumed by this node.",
                num_points: 9,
                point_attributes: &[

                    ("outcome", "success"),

                    ("signal_type", "traces"),

                    ("outcome", "success"),

                    ("signal_type", "metrics"),

                    ("outcome", "success"),

                    ("signal_type", "logs"),

                    ("outcome", "failure"),

                    ("signal_type", "traces"),

                    ("outcome", "failure"),

                    ("signal_type", "metrics"),

                    ("outcome", "failure"),

                    ("signal_type", "logs"),

                    ("outcome", "refused"),

                    ("signal_type", "traces"),

                    ("outcome", "refused"),

                    ("signal_type", "metrics"),

                    ("outcome", "refused"),

                    ("signal_type", "logs"),

                ],
                attrs_per_point: 2,
            },

            CounterMetricDef {
                name: "node.producer.items",
                unit: "{item}",
                description: "Items produced by this node.",
                num_points: 9,
                point_attributes: &[

                    ("outcome", "success"),

                    ("signal_type", "traces"),

                    ("outcome", "success"),

                    ("signal_type", "metrics"),

                    ("outcome", "success"),

                    ("signal_type", "logs"),

                    ("outcome", "failure"),

                    ("signal_type", "traces"),

                    ("outcome", "failure"),

                    ("signal_type", "metrics"),

                    ("outcome", "failure"),

                    ("signal_type", "logs"),

                    ("outcome", "refused"),

                    ("signal_type", "traces"),

                    ("outcome", "refused"),

                    ("signal_type", "metrics"),

                    ("outcome", "refused"),

                    ("signal_type", "logs"),

                ],
                attrs_per_point: 2,
            },

        ],

    };

    PrecomputedMetricSchema::new(&defs).ok()
}