// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// @generated by `cargo xtask generate-metrics` — do not edit manually.

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(trivial_numeric_casts)]
#![allow(clippy::needless_update)]

use otap_df_config::policy::MetricLevel;
use crate::instrument::Counter;

pub const OUTCOME_CARDINALITY: usize = 3;

pub const SIGNAL_TYPE_CARDINALITY: usize = 3;

/// Metrics for items consumed by a pipeline node.
pub enum NodeConsumer {
    /// Active at `MetricLevel::Basic` (3 scopes).
    Basic {
        items: [Counter<u64>; 3],
        duration: [Counter<f64>; 3],
    },
    /// Active at `MetricLevel::Normal` (9 scopes).
    Normal {
        items: [Counter<u64>; 9],
        duration: [Counter<f64>; 9],
    },
    /// Active at `MetricLevel::Detailed` (9 scopes).
    Detailed {
        items: [Counter<u64>; 9],
        duration: [Counter<f64>; 9],
    },
}

impl NodeConsumer {
    /// Create a new metric set for the given level.
    #[must_use]
    pub fn new(level: MetricLevel) -> Self {
        match level {
            MetricLevel::None | MetricLevel::Basic => Self::Basic {
                items: Default::default(),
                duration: Default::default(),
            },
            MetricLevel::Normal => Self::Normal {
                items: Default::default(),
                duration: Default::default(),
            },
            MetricLevel::Detailed => Self::Detailed {
                items: Default::default(),
                duration: Default::default(),
            },
        }
    }

    /// Record a value for `node.consumer.items`.
    #[inline]
    pub fn add_items(&mut self, value: u64, outcome: usize, signal_type: usize) {
        match self {
            NodeConsumer::Basic { items, .. } => {
                items[outcome].add(value);
            }
            NodeConsumer::Normal { items, .. } => {
                items[outcome * 3 + signal_type].add(value);
            }
            NodeConsumer::Detailed { items, .. } => {
                items[outcome * 3 + signal_type].add(value);
            }
        }
    }

    /// Record a value for `node.consumer.duration`.
    #[inline]
    pub fn record_duration(&mut self, value: f64, outcome: usize, signal_type: usize) {
        match self {
            NodeConsumer::Basic { duration, .. } => {
                duration[outcome].add(value);
            }
            NodeConsumer::Normal { duration, .. } => {
                duration[outcome * 3 + signal_type].add(value);
            }
            NodeConsumer::Detailed { duration, .. } => {
                duration[outcome * 3 + signal_type].add(value);
            }
        }
    }

    /// Copy current values into a flat snapshot buffer.
    pub fn snapshot_into(&self, dest: &mut [u64]) {
        let mut offset = 0;
        match self {
            NodeConsumer::Basic { items, duration } => {
                for c in items.iter() {
                    dest[offset] = c.get();
                    offset += 1;
                }
                for c in duration.iter() {
                    dest[offset] = c.get() as u64;
                    offset += 1;
                }
            }
            NodeConsumer::Normal { items, duration } => {
                for c in items.iter() {
                    dest[offset] = c.get();
                    offset += 1;
                }
                for c in duration.iter() {
                    dest[offset] = c.get() as u64;
                    offset += 1;
                }
            }
            NodeConsumer::Detailed { items, duration } => {
                for c in items.iter() {
                    dest[offset] = c.get();
                    offset += 1;
                }
                for c in duration.iter() {
                    dest[offset] = c.get() as u64;
                    offset += 1;
                }
            }
        }
    }

    /// Reset all values for the next collection interval.
    pub fn clear(&mut self) {
        match self {
            NodeConsumer::Basic { items, duration } => {
                for c in items.iter_mut() { c.reset(); }
                for c in duration.iter_mut() { c.reset(); }
            }
            NodeConsumer::Normal { items, duration } => {
                for c in items.iter_mut() { c.reset(); }
                for c in duration.iter_mut() { c.reset(); }
            }
            NodeConsumer::Detailed { items, duration } => {
                for c in items.iter_mut() { c.reset(); }
                for c in duration.iter_mut() { c.reset(); }
            }
        }
    }

    /// Returns `true` if any value is non-zero.
    pub fn needs_flush(&self) -> bool {
        match self {
            NodeConsumer::Basic { items, duration } => {
                items.iter().any(|c| c.get() != 0u64)
                    || duration.iter().any(|c| c.get() != 0.0f64)
            }
            NodeConsumer::Normal { items, duration } => {
                items.iter().any(|c| c.get() != 0u64)
                    || duration.iter().any(|c| c.get() != 0.0f64)
            }
            NodeConsumer::Detailed { items, duration } => {
                items.iter().any(|c| c.get() != 0u64)
                    || duration.iter().any(|c| c.get() != 0.0f64)
            }
        }
    }
}

/// Metrics for items produced by a pipeline node.
pub enum NodeProducer {
    /// Active at `MetricLevel::Basic` (3 scopes).
    Basic {
        items: [Counter<u64>; 3],
        duration: [Counter<f64>; 3],
    },
    /// Active at `MetricLevel::Normal` (9 scopes).
    Normal {
        items: [Counter<u64>; 9],
        duration: [Counter<f64>; 9],
    },
    /// Active at `MetricLevel::Detailed` (9 scopes).
    Detailed {
        items: [Counter<u64>; 9],
        duration: [Counter<f64>; 9],
    },
}

impl NodeProducer {
    /// Create a new metric set for the given level.
    #[must_use]
    pub fn new(level: MetricLevel) -> Self {
        match level {
            MetricLevel::None | MetricLevel::Basic => Self::Basic {
                items: Default::default(),
                duration: Default::default(),
            },
            MetricLevel::Normal => Self::Normal {
                items: Default::default(),
                duration: Default::default(),
            },
            MetricLevel::Detailed => Self::Detailed {
                items: Default::default(),
                duration: Default::default(),
            },
        }
    }

    /// Record a value for `node.producer.items`.
    #[inline]
    pub fn add_items(&mut self, value: u64, outcome: usize, signal_type: usize) {
        match self {
            NodeProducer::Basic { items, .. } => {
                items[outcome].add(value);
            }
            NodeProducer::Normal { items, .. } => {
                items[outcome * 3 + signal_type].add(value);
            }
            NodeProducer::Detailed { items, .. } => {
                items[outcome * 3 + signal_type].add(value);
            }
        }
    }

    /// Record a value for `node.producer.duration`.
    #[inline]
    pub fn record_duration(&mut self, value: f64, outcome: usize, signal_type: usize) {
        match self {
            NodeProducer::Basic { duration, .. } => {
                duration[outcome].add(value);
            }
            NodeProducer::Normal { duration, .. } => {
                duration[outcome * 3 + signal_type].add(value);
            }
            NodeProducer::Detailed { duration, .. } => {
                duration[outcome * 3 + signal_type].add(value);
            }
        }
    }

    /// Copy current values into a flat snapshot buffer.
    pub fn snapshot_into(&self, dest: &mut [u64]) {
        let mut offset = 0;
        match self {
            NodeProducer::Basic { items, duration } => {
                for c in items.iter() {
                    dest[offset] = c.get();
                    offset += 1;
                }
                for c in duration.iter() {
                    dest[offset] = c.get() as u64;
                    offset += 1;
                }
            }
            NodeProducer::Normal { items, duration } => {
                for c in items.iter() {
                    dest[offset] = c.get();
                    offset += 1;
                }
                for c in duration.iter() {
                    dest[offset] = c.get() as u64;
                    offset += 1;
                }
            }
            NodeProducer::Detailed { items, duration } => {
                for c in items.iter() {
                    dest[offset] = c.get();
                    offset += 1;
                }
                for c in duration.iter() {
                    dest[offset] = c.get() as u64;
                    offset += 1;
                }
            }
        }
    }

    /// Reset all values for the next collection interval.
    pub fn clear(&mut self) {
        match self {
            NodeProducer::Basic { items, duration } => {
                for c in items.iter_mut() { c.reset(); }
                for c in duration.iter_mut() { c.reset(); }
            }
            NodeProducer::Normal { items, duration } => {
                for c in items.iter_mut() { c.reset(); }
                for c in duration.iter_mut() { c.reset(); }
            }
            NodeProducer::Detailed { items, duration } => {
                for c in items.iter_mut() { c.reset(); }
                for c in duration.iter_mut() { c.reset(); }
            }
        }
    }

    /// Returns `true` if any value is non-zero.
    pub fn needs_flush(&self) -> bool {
        match self {
            NodeProducer::Basic { items, duration } => {
                items.iter().any(|c| c.get() != 0u64)
                    || duration.iter().any(|c| c.get() != 0.0f64)
            }
            NodeProducer::Normal { items, duration } => {
                items.iter().any(|c| c.get() != 0u64)
                    || duration.iter().any(|c| c.get() != 0.0f64)
            }
            NodeProducer::Detailed { items, duration } => {
                items.iter().any(|c| c.get() != 0u64)
                    || duration.iter().any(|c| c.get() != 0.0f64)
            }
        }
    }
}

