// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// @generated by `cargo xtask generate-metrics` — do not edit manually.

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(trivial_numeric_casts)]
#![allow(clippy::needless_update)]

use otap_df_config::policy::MetricLevel;
use crate::instrument::Counter;
use crate::self_metrics::precomputed::{
    DimensionInfo, MetricInfo, PrecomputedMetricSchema,
};
use otap_df_pdata::otlp::metrics::MetricType;

pub const OUTCOME_CARDINALITY: usize = 3;

pub const SIGNAL_TYPE_CARDINALITY: usize = 3;

/// Metrics for items consumed by a pipeline node.
pub enum NodeConsumer {
    /// Active at `MetricLevel::Basic` (1 scopes).
    Basic {
        items: [Counter<u64>; 1],
        duration: [Counter<f64>; 1],
    },
    /// Active at `MetricLevel::Normal` (3 scopes).
    Normal {
        items: [Counter<u64>; 3],
        duration: [Counter<f64>; 3],
    },
    /// Active at `MetricLevel::Detailed` (9 scopes).
    Detailed {
        items: [Counter<u64>; 9],
        duration: [Counter<f64>; 9],
    },
}

impl NodeConsumer {
    /// Create a new metric set for the given level.
    #[must_use]
    pub fn new(level: MetricLevel) -> Self {
        match level {
            MetricLevel::None | MetricLevel::Basic => Self::Basic {
                items: Default::default(),
                duration: Default::default(),
            },
            MetricLevel::Normal => Self::Normal {
                items: Default::default(),
                duration: Default::default(),
            },
            MetricLevel::Detailed => Self::Detailed {
                items: Default::default(),
                duration: Default::default(),
            },
        }
    }

    /// Record a value for `node.consumer.items`.
    #[inline]
    pub fn add_items(&mut self, value: u64, outcome: usize, signal_type: usize) {
        match self {
            NodeConsumer::Basic { items, .. } => {
                items[0].add(value);
            }
            NodeConsumer::Normal { items, .. } => {
                items[outcome].add(value);
            }
            NodeConsumer::Detailed { items, .. } => {
                items[outcome * 3 + signal_type].add(value);
            }
        }
    }

    /// Record a value for `node.consumer.duration`.
    #[inline]
    pub fn record_duration(&mut self, value: f64, outcome: usize, signal_type: usize) {
        match self {
            NodeConsumer::Basic { duration, .. } => {
                duration[0].add(value);
            }
            NodeConsumer::Normal { duration, .. } => {
                duration[outcome].add(value);
            }
            NodeConsumer::Detailed { duration, .. } => {
                duration[outcome * 3 + signal_type].add(value);
            }
        }
    }

    /// Copy current values into a flat snapshot buffer.
    pub fn snapshot_into(&self, dest: &mut [u64]) {
        let mut offset = 0;
        match self {
            NodeConsumer::Basic { items, duration } => {
                for c in items.iter() {
                    dest[offset] = c.get();
                    offset += 1;
                }
                for c in duration.iter() {
                    dest[offset] = c.get() as u64;
                    offset += 1;
                }
            }
            NodeConsumer::Normal { items, duration } => {
                for c in items.iter() {
                    dest[offset] = c.get();
                    offset += 1;
                }
                for c in duration.iter() {
                    dest[offset] = c.get() as u64;
                    offset += 1;
                }
            }
            NodeConsumer::Detailed { items, duration } => {
                for c in items.iter() {
                    dest[offset] = c.get();
                    offset += 1;
                }
                for c in duration.iter() {
                    dest[offset] = c.get() as u64;
                    offset += 1;
                }
            }
        }
    }

    /// Reset all values for the next collection interval.
    pub fn clear(&mut self) {
        match self {
            NodeConsumer::Basic { items, duration } => {
                for c in items.iter_mut() { c.reset(); }
                for c in duration.iter_mut() { c.reset(); }
            }
            NodeConsumer::Normal { items, duration } => {
                for c in items.iter_mut() { c.reset(); }
                for c in duration.iter_mut() { c.reset(); }
            }
            NodeConsumer::Detailed { items, duration } => {
                for c in items.iter_mut() { c.reset(); }
                for c in duration.iter_mut() { c.reset(); }
            }
        }
    }

    /// Returns `true` if any value is non-zero.
    pub fn needs_flush(&self) -> bool {
        match self {
            NodeConsumer::Basic { items, duration } => {
                items.iter().any(|c| c.get() != 0u64)
                    || duration.iter().any(|c| c.get() != 0.0f64)
            }
            NodeConsumer::Normal { items, duration } => {
                items.iter().any(|c| c.get() != 0u64)
                    || duration.iter().any(|c| c.get() != 0.0f64)
            }
            NodeConsumer::Detailed { items, duration } => {
                items.iter().any(|c| c.get() != 0u64)
                    || duration.iter().any(|c| c.get() != 0.0f64)
            }
        }
    }
    /// Build the precomputed OTAP schema for a given level.
    ///
    /// Returns the metrics table, scope attrs table, and NDP layout
    /// metadata. Called once at init time.
    pub fn precomputed_schema(level: MetricLevel) -> Result<PrecomputedMetricSchema, arrow::error::ArrowError> {
        const METRICS: &[MetricInfo] = &[
            MetricInfo {
                name: "node.consumer.items",
                description: "Items consumed by this node.",
                unit: "{item}",
                metric_type: MetricType::Sum,
                aggregation_temporality: Some(1),
                is_monotonic: Some(true),
            },
            MetricInfo {
                name: "node.consumer.duration",
                description: "Time to consume items.",
                unit: "ns",
                metric_type: MetricType::ExponentialHistogram,
                aggregation_temporality: Some(1),
                is_monotonic: None,
            },
        ];

        const DIMENSIONS: &[DimensionInfo] = &[
            DimensionInfo { key: "outcome", values: &["success", "failure", "refused"] },
            DimensionInfo { key: "signal_type", values: &["logs", "metrics", "traces"] },
        ];

        let active_dims: &[usize] = match level {
            MetricLevel::None | MetricLevel::Basic => &[],
            MetricLevel::Normal => &[0],
            MetricLevel::Detailed => &[0, 1],
        };

        PrecomputedMetricSchema::build(METRICS, DIMENSIONS, active_dims)
    }

    /// Number of scopes at each level for `NodeConsumer`.
    pub const SCOPES_BASIC: usize = 1;
    pub const SCOPES_NORMAL: usize = 3;
    pub const SCOPES_DETAILED: usize = 9;
}

/// Metrics for items produced by a pipeline node.
pub enum NodeProducer {
    /// Active at `MetricLevel::Basic` (1 scopes).
    Basic {
        items: [Counter<u64>; 1],
        duration: [Counter<f64>; 1],
    },
    /// Active at `MetricLevel::Normal` (3 scopes).
    Normal {
        items: [Counter<u64>; 3],
        duration: [Counter<f64>; 3],
    },
    /// Active at `MetricLevel::Detailed` (9 scopes).
    Detailed {
        items: [Counter<u64>; 9],
        duration: [Counter<f64>; 9],
    },
}

impl NodeProducer {
    /// Create a new metric set for the given level.
    #[must_use]
    pub fn new(level: MetricLevel) -> Self {
        match level {
            MetricLevel::None | MetricLevel::Basic => Self::Basic {
                items: Default::default(),
                duration: Default::default(),
            },
            MetricLevel::Normal => Self::Normal {
                items: Default::default(),
                duration: Default::default(),
            },
            MetricLevel::Detailed => Self::Detailed {
                items: Default::default(),
                duration: Default::default(),
            },
        }
    }

    /// Record a value for `node.producer.items`.
    #[inline]
    pub fn add_items(&mut self, value: u64, outcome: usize, signal_type: usize) {
        match self {
            NodeProducer::Basic { items, .. } => {
                items[0].add(value);
            }
            NodeProducer::Normal { items, .. } => {
                items[outcome].add(value);
            }
            NodeProducer::Detailed { items, .. } => {
                items[outcome * 3 + signal_type].add(value);
            }
        }
    }

    /// Record a value for `node.producer.duration`.
    #[inline]
    pub fn record_duration(&mut self, value: f64, outcome: usize, signal_type: usize) {
        match self {
            NodeProducer::Basic { duration, .. } => {
                duration[0].add(value);
            }
            NodeProducer::Normal { duration, .. } => {
                duration[outcome].add(value);
            }
            NodeProducer::Detailed { duration, .. } => {
                duration[outcome * 3 + signal_type].add(value);
            }
        }
    }

    /// Copy current values into a flat snapshot buffer.
    pub fn snapshot_into(&self, dest: &mut [u64]) {
        let mut offset = 0;
        match self {
            NodeProducer::Basic { items, duration } => {
                for c in items.iter() {
                    dest[offset] = c.get();
                    offset += 1;
                }
                for c in duration.iter() {
                    dest[offset] = c.get() as u64;
                    offset += 1;
                }
            }
            NodeProducer::Normal { items, duration } => {
                for c in items.iter() {
                    dest[offset] = c.get();
                    offset += 1;
                }
                for c in duration.iter() {
                    dest[offset] = c.get() as u64;
                    offset += 1;
                }
            }
            NodeProducer::Detailed { items, duration } => {
                for c in items.iter() {
                    dest[offset] = c.get();
                    offset += 1;
                }
                for c in duration.iter() {
                    dest[offset] = c.get() as u64;
                    offset += 1;
                }
            }
        }
    }

    /// Reset all values for the next collection interval.
    pub fn clear(&mut self) {
        match self {
            NodeProducer::Basic { items, duration } => {
                for c in items.iter_mut() { c.reset(); }
                for c in duration.iter_mut() { c.reset(); }
            }
            NodeProducer::Normal { items, duration } => {
                for c in items.iter_mut() { c.reset(); }
                for c in duration.iter_mut() { c.reset(); }
            }
            NodeProducer::Detailed { items, duration } => {
                for c in items.iter_mut() { c.reset(); }
                for c in duration.iter_mut() { c.reset(); }
            }
        }
    }

    /// Returns `true` if any value is non-zero.
    pub fn needs_flush(&self) -> bool {
        match self {
            NodeProducer::Basic { items, duration } => {
                items.iter().any(|c| c.get() != 0u64)
                    || duration.iter().any(|c| c.get() != 0.0f64)
            }
            NodeProducer::Normal { items, duration } => {
                items.iter().any(|c| c.get() != 0u64)
                    || duration.iter().any(|c| c.get() != 0.0f64)
            }
            NodeProducer::Detailed { items, duration } => {
                items.iter().any(|c| c.get() != 0u64)
                    || duration.iter().any(|c| c.get() != 0.0f64)
            }
        }
    }
    /// Build the precomputed OTAP schema for a given level.
    ///
    /// Returns the metrics table, scope attrs table, and NDP layout
    /// metadata. Called once at init time.
    pub fn precomputed_schema(level: MetricLevel) -> Result<PrecomputedMetricSchema, arrow::error::ArrowError> {
        const METRICS: &[MetricInfo] = &[
            MetricInfo {
                name: "node.producer.items",
                description: "Items produced by this node.",
                unit: "{item}",
                metric_type: MetricType::Sum,
                aggregation_temporality: Some(1),
                is_monotonic: Some(true),
            },
            MetricInfo {
                name: "node.producer.duration",
                description: "Time to produce items.",
                unit: "ns",
                metric_type: MetricType::ExponentialHistogram,
                aggregation_temporality: Some(1),
                is_monotonic: None,
            },
        ];

        const DIMENSIONS: &[DimensionInfo] = &[
            DimensionInfo { key: "outcome", values: &["success", "failure", "refused"] },
            DimensionInfo { key: "signal_type", values: &["logs", "metrics", "traces"] },
        ];

        let active_dims: &[usize] = match level {
            MetricLevel::None | MetricLevel::Basic => &[],
            MetricLevel::Normal => &[0],
            MetricLevel::Detailed => &[0, 1],
        };

        PrecomputedMetricSchema::build(METRICS, DIMENSIONS, active_dims)
    }

    /// Number of scopes at each level for `NodeProducer`.
    pub const SCOPES_BASIC: usize = 1;
    pub const SCOPES_NORMAL: usize = 3;
    pub const SCOPES_DETAILED: usize = 9;
}

