//! Sampling receiver module for reading parquet files with DataFusion-powered queries
//! 
//! This module provides functionality to read parquet files generated by the 
//! `parquet_exporter` and process them using flexible SQL queries with DataFusion,
//! supporting both pass-through and advanced sampling operations.

pub mod config;
pub mod error;
pub mod sampling_receiver;

// Sample code for UDF implementation - disabled until DataFusion is properly integrated
// #[allow(dead_code)]
// mod sampler_udf;

// Re-export the main receiver and factory
pub use sampling_receiver::{SamplingReceiver, SAMPLING_RECEIVER_FACTORY, SAMPLING_RECEIVER_URN};
